name: Generate Snake

on:
  schedule:
    # A cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: karolinerebeca
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no branch "output"
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
